# 文件: .github/workflows/update-market-data-batch-2.yml
# 版本: Batch Processing - Batch 2 (Stocks 51-100)
name: Update S&P 500 Market Data - Batch 2 (51-100)

on:
  schedule:
    # 每15分钟开始第二批处理，延迟15分钟 (周一至周五, UTC 13-20点)
    - cron: '15,30,45,0 13-20 * * 1-5'
    # 闭市后最终运行
    - cron: '5 21 * * 1-5'
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode for detailed logs?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

# 防止并发执行，避免数据库冲突和API限制问题
concurrency:
  group: market-data-update-batch-2
  cancel-in-progress: false

jobs:
  update_sp500_batch_2:
    name: "🚀 Update S&P 500 Data - Batch 2 (51-100)"
    runs-on: ubuntu-latest
    timeout-minutes: 8 # 50只股票，时间缩短
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      DEBUG: ${{ github.event.inputs.debug_mode || 'false' }}
      BATCH_START: 51
      BATCH_END: 100
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Health check - Verify API and DB connectivity
        run: |
          echo "🔍 Checking Finnhub API connectivity..."
          curl -f "https://finnhub.io/api/v1/quote?symbol=AAPL&token=$FINNHUB_API_KEY" || exit 1
          echo "✅ Finnhub API is accessible"
          
      - name: Run S&P 500 Update Script - Batch 2
        run: |
          echo "🚀 Starting S&P 500 market data update - Batch 2 (stocks 51-100)..."
          echo "📊 Expected runtime: 2-3 minutes for 50 stocks"
          node _scripts/update-market-data-finnhub.mjs
          
      - name: Verify Update Success
        run: |
          echo "✅ S&P 500 Batch 2 update completed successfully"
          echo "📈 Next batch will start in 10 minutes"