# 文件路径: .github/workflows/scheduled_update.yml

name: Update Stock Data & Dynamic Tags

on:
  # 1. 定时触发：每天 UTC 时间 8点 (北京时间下午4点) 运行一次
  schedule:
    - cron: '0 8 * * *'
    
  # 2. 我们依然保留手动触发，方便未来需要时进行立即更新
  workflow_dispatch:

jobs:
  update-database-job:
    # ... (jobs 部分的所有内容，和之前完全一样，无需任何修改)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run database update script
        env:
          # ... (所有 secrets)
        run: node _scripts/update-database.js