name: Update Company Profiles (Weekly)

on:
  schedule:
    - cron: '0 2 * * 0'  # 每周日凌晨2点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-profiles:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 2小时超时
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run company profiles update script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: node _scripts/update-company-profiles.mjs
        
      - name: Notify on failure
        if: failure()
        run: |
          echo "Company profiles update failed!"
          echo "Please check the logs and fix any issues."