name: Update Stock Data

on:
  schedule:
    # 每天美股开盘前更新 (UTC 13:00 = EST 8:00 AM)
    - cron: '0 13 * * 1-5'
  workflow_dispatch: # 允许手动触发

jobs:
  update-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Call Vercel API to update stock data
      run: |
        echo "Updating stock data..."
        VERCEL_URL="${{ secrets.VERCEL_URL }}"
        if [ -z "$VERCEL_URL" ]; then
          echo "Error: VERCEL_URL secret is not set"
          exit 1
        fi
        curl --fail --max-time 300 -X POST \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
          -H "Content-Type: application/json" \
          "${VERCEL_URL}/api/update-data"
      env:
        VERCEL_URL: ${{ secrets.VERCEL_URL }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        
    - name: Verify update completion
      run: |
        echo "Stock data update completed successfully!"
        echo "Timestamp: $(date)"