# /.github/workflows/scheduled_update.yml

name: Scheduled Database Update

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    # *** 核心修复：使用 GitHub 上真实的仓库名 'Stock-Tag-Explorer-01' ***
    defaults:
      run:
        working-directory: ./Stock-Tag-Explorer-01

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # ** 核心修复：同样，使用真实的仓库名 **
          cache-dependency-path: 'Stock-Tag-Explorer-01/package-lock.json'

      # 现在，所有后续的 run 命令都会在正确的子目录中执行
      - name: Install dependencies
        run: npm install

      - name: Run database update script
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: node _scripts/update-database.jss