name: Update All Financials & Tags (Low Frequency)

on:
  schedule:
    - cron: '0 8 * * *'  # 每天北京时间下午4点 (UTC+8)
  workflow_dispatch:  # 允许手动触发

jobs:
  update-all:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3小时超时，因为要处理所有股票
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run full daily update script
        env:
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
        run: node _scripts/update-all-financials-and-tags.mjs